# fluentd/Dockerfile
FROM fluent/fluentd:v1.14-1
# RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-rdoc", "--no-ri", "--version", "1.9.2"]
#made changes need to discuss
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--user-install", "-N", "--version", "1.9.2"]